### ISSUE TITLE
Suggestions for how to isolate messages for a single tenant web app when MassTransit uses multiple exchanges

### ISSUE THREAD

**Issue by flipdoubt** [MassTransit/Sample-SignalR#2]
In our existing RabbitMq implementations for a single tenant app, we isolate each web app to its own RabbitMq exchange so all messages belong to the same app. Building on Sample-SignalR chat example on a RabbitMq server hosting multiple apps, how can we isolate messages to a single app when Sample-SignalR creates multiple exchanges? Is the suggestion to use one virtual host per app?

With two web servers (both running on localhost) serving one app locally, MT creates 15 exchanges where we tried to isolate all communication within a single exchange.
![image](https://user-images.githubusercontent.com/810378/120246751-2d14d400-c23f-11eb-84f2-02b8e6b40b44.png)

**Comment by phatboyg** [comment]
Yes. Split them up by virtual host. 

But realize if there is a need to communicate via RabbitMQ between applications, you're creating additional complexity by having things split up across virtual hosts.

**Comment by flipdoubt** [comment]
@phatboyg, thanks for your reply. Perhaps it is better to say I want to isolate tenants rather than apps, so all the apps belonging to one tenant would be on the same virtual host.

Is there any way to normalize these exchange names by providing a prefix or affecting the exchange name in any way?

**Comment by phatboyg** [comment]
> Is there any way to normalize these exchange names by providing a prefix or affecting the exchange name in any way?

You can modify the [message topology](https://masstransit-project.com/advanced/topology/message.html) to change message type exchange names, and you can customize the endpoint name formatter to change the receive endpoints that are configured.
